# -*- coding: utf-8 -*-
"""palindromo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ec-eK0U5shPSZfvJYpahnoa0wT6RiQPk
"""

igual, aux = 0, 0
texto = input("Ingrese la palabra que desea evaluar: ")
#Quitamos los espacios en blanco

textoaux = texto.replace(" ", "")
for ind in reversed(range(0, len(textoaux))):
  if textoaux[ind].lower() == textoaux[aux].lower():
    igual += 1
  else:
    break
  aux += 1

if len(textoaux) == igual:
  print("El texto es palindromo!")
else:
  print("El texto no es palindromo!")